(function(){
  'use strict';
  var app=document.getElementById('app'), modal=document.getElementById('modal'), body=document.getElementById('modal-body');
  var datasets={worlds:window.CITY_V2||[],traits:window.TRAITS_V2||[],inventions:Object.keys(window.DOSSIER_V2||{}).map(function(k){return window.DOSSIER_V2[k]}),chronicles:window.CHRONICLES_V2||[]};
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
  function name(o){return o.name||o.title||'Untitled'}
  function card(o,type){return '<article class="card"><span class="tag">'+esc(o.canon||o.kind||'CONCEPT')+'</span><h3>'+esc(name(o))+'</h3><p class="muted">'+esc(o.d||o.solution||'') .slice(0,220)+'</p><div class="actions"><button class="btn" data-open="'+esc(type)+'" data-id="'+esc(o.id||'')+'">Open file</button></div></article>'}
  function render(route,query){var title=route==='home'?'Enter the SOVERSE':route.charAt(0).toUpperCase()+route.slice(1);if(route==='home'){app.innerHTML='<section class="hero"><span class="tag">CHRISTOPHER “SO” ROUSSEAU</span><h1>SO</h1><p class="lede">The music. The universe. Enter. Explore worlds, identity, inventions, stories and lingo — connected by FAITH + KNOWLEDGE.</p><div class="actions"><button class="btn" data-route="worlds">Explore Worlds</button><button class="btn" data-route="inventions">Visit Invention Lab</button></div></section><h2>Featured universe</h2><div class="grid">'+datasets.worlds.slice(0,3).map(function(o){return card(o,'world')}).join('')+'</div>';return}var list=datasets[route]||[];if(query)list=list.filter(function(o){return JSON.stringify(o).toLowerCase().indexOf(query.toLowerCase())>-1});app.innerHTML='<h1>'+esc(title)+'</h1><p class="lede">'+list.length+' entries · device-local static catalog</p><div class="grid">'+(list.length?list.map(function(o){return card(o,route==='worlds'?'world':route==='inventions'?'invention':route==='chronicles'?'chronicle':'trait')}).join(''):'<div class="empty">No matching entries yet.</div>')+'</div>'}
  function open(type,id){var list=datasets[type==='world'?'worlds':type==='invention'?'inventions':type==='chronicle'?'chronicles':'traits'];var o=list.filter(function(x){return String(x.id)===String(id)})[0];if(!o)return;body.innerHTML='<span class="tag">'+esc(o.canon||o.kind||'CONCEPT')+'</span><h2>'+esc(name(o))+'</h2><p>'+esc(o.d||o.solution||'')+'</p>'+(o.tagline?'<p class="gold"><b>'+esc(o.tagline)+'</b></p>':'')+(o.secret?'<h3>Hidden door</h3><p>'+esc(o.secret)+'</p>':'')+(o.spots?'<h3>Places</h3><ul>'+o.spots.map(function(s){return '<li><b>'+esc(s.name)+'</b> — '+esc(s.d)+'</li>'}).join('')+'</ul>':'')+(o.safety?'<h3>Safety and status</h3><p>'+esc(o.safety)+'</p>':'');modal.hidden=false}
  function route(){var r=location.hash.slice(1)||'home';if(!/^(home|worlds|traits|inventions|chronicles)$/.test(r))r='home';render(r,document.getElementById('search').value)}
  document.addEventListener('click',function(e){var r=e.target.closest('[data-route]'),o=e.target.closest('[data-open]');if(r){location.hash=r.dataset.route}if(o)open(o.dataset.open,o.dataset.id)});document.getElementById('search').addEventListener('input',route);document.getElementById('close').onclick=function(){modal.hidden=true};modal.addEventListener('click',function(e){if(e.target===modal)modal.hidden=true});window.addEventListener('hashchange',route);route();
})();
